### ISSUE TITLE
Add a way to use the library in the browser

### ISSUE THREAD

**Issue by jcubic** [timoxley/wcwidth#2]
It would be nice if the library could be use in the browser and not only in node.

You can create browser file using this:

creating file `wcwidth.js`
```javascript
window.wcwidth = require('./');
```
calling:
```
npm install -g browserify
mkdir dist
browserify wcwidth.js -o dist/wcwidth.js
```

or you can add browserify as dev dependency and add npm script that will run:
```
node node_modules/browserify/bin/cmd.js
```

**Comment by timoxley** [comment]
Most users have their own workflow for consuming node modules in the browser and it's very easy to generate these types of things online, e.g. if you want to consume this via a script tag over a CDN you can use:

https://wzrd.in/standalone/wcwidth@%5E1.0.1

**Comment by jcubic** [comment]
The url don't work anymore rawgit.com will be shutting down so the only way to have this build in codepen is to create fork and publish to npm. Can you reconsider creating UMD package to be used with unpkg CND.
